[[redirects]]
  from = "/nintendo-switch/"
  to = "/nintendo-switch/1"
  status = 301
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  force = true
  status = 200
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/medabots/"
  to = "/medabots/*"
  status = 410
  force = true

[functions]
  directory = "functions"