local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://talale.it"
display_url: "https://talale.it"
logo_url: "https://talale.it/icon.png"
locale: "it"

collections:
  - name: "projects"
    label: "Progetti"
    label_singular: "Progetto"
    description: "Esempi di lavoro"
    folder: "src/content/projects"
    create: true
    sortable_fields: ["pubDate", "title"]
    fields:
      - { label: "Thumb", name: "thumb", widget: "image" }
      - { label: "Titolo", name: "title", widget: "string", required: true }
      - {
          label: "Descrizione",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Link", name: "link", widget: "string", required: true }
      - {
          label: "Data pubblicazione",
          name: "pubDate",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Portfolio",
          name: "portfolio",
          widget: "boolean",
          default: false,
        }
      - label: "Galleria"
        name: "gallery"
        widget: "list"
        required: true
        field: { label: "Immagine", name: "image", widget: "image" }
  - name: "settings"
    label: "Impostazioni"
    files:
      - name: "general"
        label: "Generali"
        file: "src/config/general.json"
        editor:
          preview: false
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Sottotitolo", name: "subtitle", widget: "string" }
          - { label: "Motto", name: "motto", widget: "string" }
          - { label: "Descrizione", name: "description", widget: "text" }
          - { label: "CTA", name: "cta", widget: "string" }
          - { label: "Biografia", name: "biography", widget: "markdown" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Whatsapp URL", name: "waUrl", widget: "string" }
          - label: "Google Maps"
            name: "googleMaps"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Google Calendar"
            name: "googleCalendar"
            widget: "object"
            collapsed: true
            fields:
              - { label: "URL", name: "url", widget: "string" }
              - { label: "CTA", name: "cta", widget: "string" }
          - label: "Messagebox"
            name: "messagebox"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Placeholder", name: "placeholder", widget: "string" }
              - { label: "Conferma", name: "success", widget: "string" }
              - { label: "Errore", name: "error", widget: "string" }
          - label: "Blog"
            name: "blog"
            widget: "object"
            collapsed: true
            fields:
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Categoria", name: "category", widget: "string" }
          - label: "IGDB"
            name: "igdb"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Console", name: "console", widget: "string" }
              - {
                  label: "Offset Data (Da)",
                  hint: "Numero di mesi rispetto alla data di deploy",
                  name: "dateFromNMonths",
                  widget: "string",
                  step: 1,
                }
              - {
                  label: "Offset Data (A)",
                  hint: "Numero di mesi rispetto alla data di deploy",
                  name: "dateToNMonths",
                  widget: "string",
                  step: 1,
                }
              - {
                  label: "Giochi per Pagina",
                  name: "gamesPerPage",
                  widget: "number",
                  value_type: "int",
                  min: 1,
                }
      - name: "freelance"
        label: "Freelance"
        file: "src/config/freelance.json"
        editor:
          preview: false
        fields:
          - { label: "PIva", name: "piva", widget: "string" }
          - label: "Prezzi"
            label_singular: "Prezzo"
            name: "prices"
            widget: "list"
            max: 3
            min: 3
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Descrizione", name: "description", widget: "string" }
              - {
                  label: "Info",
                  name: "info",
                  widget: "string",
                  required: false,
                }
              - { label: "Cifra", name: "amount", widget: "number", default: 0 }
              - {
                  label: "Informazioni Cifra",
                  name: "amountInfo",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Prezzo base",
                  name: "plus",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "Features",
                  name: "features",
                  widget: "list",
                  hint: "Comma separated",
                  summary: "{{name}}",
                }
              - {
                  label: "Include servizi base",
                  name: "includesBaseServices",
                  widget: "boolean",
                  default: false,
                }
              - {
                  label: "Mesi di manutenzioni inclusi",
                  name: "supportMonthsIncluded",
                  widget: "number",
                  default: 0,
                }
          - label: "Servizi di assistenza"
            label_singular: "servizio"
            name: "supportServices"
            widget: "list"
            min: 6
            max: 6
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Icona", name: "icon", widget: "string" }
          - label: "Frameworks"
            label_singular: "Framework"
            name: "frameworks"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Logo", name: "logo", widget: "image" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Features"
            label_singular: "Feature"
            name: "features"
            widget: "list"
            allow_add: true
            fields:
              - { label: "Titolo", name: "title", widget: "string" }
              - {
                  label: "Descrizione",
                  name: "description",
                  widget: "markdown",
                }
