local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://talale.it"
display_url: "https://talale.it"
logo_url: "https://talale.it/icon.png"
locale: "it"

collections:
  - name: "projects"
    label: "Progetti"
    label_singular: "Progetto"
    description: "Esempi di lavoro"
    folder: "src/content/projects"
    create: true
    sortable_fields: [ "pubDate", "title"]
    fields:
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Titolo", name: "title", widget: "string", required: true }
      - { label: "Descrizione", name: "description", widget: "text", required: true }
      - { label: "Link", name: "link", widget: "string", required: true }
      - { label: "Data pubblicazione", name: "pubDate", widget: "datetime", required: true }
      - { label: "Portfolio", name: "portfolio", widget: "boolean", default: false }
      - label: "Galleria"
        name: "gallery"
        widget: "list"
        required: true
        field: { label: "Immagine", name: "image", widget: "image"}
  - name: "certificates"
    label: "Attestati"
    label_singular: "Attestato"
    description: "Attestati e corsi"
    folder: "src/content/certificates"
    create: true
    sortable_fields: [ "obtainedAt", "name"]
    fields:
      - { label: "Logo", name: "logo", widget: "image", required: false }
      - { label: "Titolo", name: "title", widget: "string", required: true }
      - { label: "Immagine", name: "image", widget: "image" }
      - { label: "Data", name: "obtainedAt", widget: "datetime", required: true }
      - { label: "Nascosto", name: "hidden", widget: "boolean", default: false }
  - name: "settings"
    label: "Impostazioni"
    files:
      - name: "site_config"
        label: "Configurazione Sito"
        file: "src/site_config.json"
        editor:
          preview: false
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Sottotitolo", name: "subtitle", widget: "string" }
          - { label: "Motto", name: "motto", widget: "string"}
          - { label: "Descrizione", name: "description", widget: "text"}
          - { label: "Blog URL", name: "blogUrl", widget: "string" }
          - { label: "Categoria Blog", name: "blogCategory", widget: "string" }
          - { label: "CTA", name: "cta", widget: "string" }
          - { label: "Google Calendar URL", name: "google_calendar_url", widget: "string" }
          - { label: "Google Calendar CTA", name: "google_calendar_cta", widget: "string" }
          - { label: "Biografia", name: "biography", widget: "markdown" }
          - { label: "MessageBox - Placeholder", name: "messageBoxPlaceholder", widget: "string" }
          - { label: "MessageBox - Conferma", name: "messageBoxSuccess", widget: "string" }
          - { label: "MessageBox - Errore", name: "messageBoxError", widget: "string" }
          - { label: "Giochi per Pagina", name: "gamesPerPage", widget: "number", value_type: "int", min: 1 }
          - label: "Features"
            name: "features"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Descrizione", name: "description", widget: "markdown"}
          - label: "Frameworks"
            name: "frameworks"
            widget: "list"
            allow_add: true
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "URL", name: "url", widget: "string"}
          - label: "Prezzi"
            name: "prices"
            widget: "object"
            allow_add: true
            fields:
              - {label: "Standard", name: "standard", widget: "number", default: 0}
              - {label: "Custom", name: "custom", widget: "number", default: 0}
              - {label: "Supporto", name: "support", widget: "number", default: 0}