local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://talale.it"
display_url: "https://talale.it"
logo_url: "https://talale.it/icon.png"
locale: "it"

collections:
  - name: "settings"
    label: "Impostazioni"
    files:
      - name: "site_config"
        label: "Configurazione Sito"
        file: "src/site_config.json"
        editor:
          preview: false
        fields:
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Sottotitolo", name: "subtitle", widget: "string" }
          - { label: "Descrizione", name: "description", widget: "string"}
          - { label: "Blog URL", name: "blogUrl", widget: "string" }
          - { label: "Categoria Blog", name: "blogCategory", widget: "string" }
          - { label: "CTA", name: "cta", widget: "string" }
          - { label: "Biografia", name: "biography", widget: "string" }
          - { label: "Prefisso Blocco Codice", name: "defaultCodePrefix", widget: "string" }
          - { label: "MessageBox - Placeholder", name: "messageBoxPlaceholder", widget: "string" }
          - { label: "MessageBox - Conferma", name: "messageBoxSuccess", widget: "string" }
          - { label: "MessageBox - Errore", name: "messageBoxError", widget: "string" }
          - { label: "Giochi per Pagina", name: "gamesPerPage", widget: "number", value_type: "int", min: 1 }
  - name: "projects"
    label: "Progetti"
    label_singular: "Progetto"
    description: "Esempi di lavoro"
    folder: "src/content/projects"
    create: true
    sortable_fields: [ "pubDate", "title"]
    fields:
      - { label: "Titolo", name: "title", widget: "string", required: true }
      - { label: "Descrizione", name: "description", widget: "text", required: true }
      - { label: "Link", name: "link", widget: "string", required: true }
      - { label: "Data pubblicazione", name: "pubDate", widget: "datetime", required: true }
      - label: "Galleria"
        name: "gallery"
        widget: "list"
        field: { label: "Immagine", name: "image", widget: "image"}
